version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/Inventory
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/product-crud-app
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: {}
